server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.101.155.185:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Ycdb9163.

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


